export const dummy_models = [
  {
    is_active: false,
    name: "gzsl_model",
    layers: [
      {
        layer_name: "NetNet",
        input_shape: "[1,78]",
        output_shape: "[1,16]",
        params: 1736,
        kernel_size: "",
      },
      {
        layer_name: "├─Linear:1-1",
        input_shape: "[1,78]",
        output_shape: "[1,512]",
        params: 40448,
        kernel_size: "",
      },
      {
        layer_name: "├─LeakyReLU:1-2",
        input_shape: "[1,512]",
        output_shape: "[1,512]",
        params: 0,
        kernel_size: "",
      },
      {
        layer_name: "├─Linear:1-3",
        input_shape: "[1,512]",
        output_shape: "[1,256]",
        params: 131328,
        kernel_size: "",
      },
      {
        layer_name: "├─LeakyReLU:1-4",
        input_shape: "[1,256]",
        output_shape: "[1,256]",
        params: 0,
        kernel_size: "",
      },
      {
        layer_name: "├─Linear:1-5",
        input_shape: "[1,256]",
        output_shape: "[1,100]",
        params: 25700,
        kernel_size: "",
      },
      {
        layer_name: "├─LeakyReLU:1-6",
        input_shape: "[1,100]",
        output_shape: "[1,100]",
        params: 0,
        kernel_size: "",
      },
      {
        layer_name: "├─Linear:1-7",
        input_shape: "[1,100]",
        output_shape: "[1,16]",
        params: 1616,
        kernel_size: "",
      },
    ],
    total_params: 200828,
    trainable_params: 199228,
    non_trainable_params: 1600,
    total_mult_adds: 0.2,
    input_size_MB: 0.0,
    forward_backward_pass_size_MB: 0.01,
    params_size_MB: 0.8,
    estimated_total_size_MB: 0.8,
  },
  {
    is_active: true,
    name: "zsl_model",
    layers: [
      {
        layer_name: "Sequential",
        input_shape: "[1,78]",
        output_shape: "[1,100]",
        params: 0,
        kernel_size: "",
      },
      {
        layer_name: "├─Linear:1-1",
        input_shape: "[1,78]",
        output_shape: "[1,512]",
        params: 40448,
        kernel_size: "",
      },
      {
        layer_name: "├─BatchNorm1d:1-2",
        input_shape: "[1,512]",
        output_shape: "[1,512]",
        params: 1024,
        kernel_size: "",
      },
      {
        layer_name: "├─Linear:1-3",
        input_shape: "[1,512]",
        output_shape: "[1,256]",
        params: 131328,
        kernel_size: "",
      },
      {
        layer_name: "├─BatchNorm1d:1-4",
        input_shape: "[1,256]",
        output_shape: "[1,256]",
        params: 512,
        kernel_size: "",
      },
      {
        layer_name: "├─Linear:1-5",
        input_shape: "[1,256]",
        output_shape: "[1,100]",
        params: 25700,
        kernel_size: "",
      },
      {
        layer_name: "├─BatchNorm1d:1-6",
        input_shape: "[1,100]",
        output_shape: "[1,100]",
        params: 200,
        kernel_size: "",
      },
      {
        layer_name: "├─LeakyReLU:1-7",
        input_shape: "[1,100]",
        output_shape: "[1,100]",
        params: 0,
        kernel_size: "",
      },
    ],
    total_params: 199212,
    trainable_params: 199212,
    non_trainable_params: 0,
    total_mult_adds: 0.2,
    input_size_MB: 0.0,
    forward_backward_pass_size_MB: 0.01,
    params_size_MB: 0.8,
    estimated_total_size_MB: 0.81,
  },
];
