name: Update Docker Image

on:
  push:
    branches:
      - master

jobs:
  update-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Build Docker image
        run: docker image build .

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: docker push packetbase/frontend
